### ISSUE TITLE
A way to add arguments to MD_RENDERER

### ISSUE THREAD

**Issue by bartekpacia** [maciejzj/ssb#6]
I'd like to customize the call to `pandoc`, e.g. by using a template:

```
pandoc --template my_template.md
```

I tried doing:

```
export MD_RENDERER="pandoc --template my_template.md"
```

but it fails for [this reason](https://unix.stackexchange.com/q/444946/417321).

Therefore I think an additional option called `MD_RENDERER_ARGS` could be added (just my first idea, maybe there's a better way).

**Comment by maciejzj** [comment]
Sorry for responding after some time, I was rather busy.

I see the problem, I believe that it can be fix with using `eval` – something like:

```diff
diff --git a/ssb b/ssb
index e5186b9..4a6cdc5 100755
--- a/ssb
+++ b/ssb
@@ -304,7 +304,7 @@ make_html_files()
 		# Ignore the suggestion because tempf can be expanded immediately
 		# shellcheck disable=SC2064
 		trap "rm $tempf" 0 2 3 15
-		append_posts_list "$posts" | cat "$md_file" - | "$MD_RENDERER" > "$tempf"
+		append_posts_list "$posts" | cat "$md_file" - | eval "$MD_RENDERER" > "$tempf"
 		cat "$HEADER_PATH" "$tempf" "$FOOTER_PATH" > "$output_file"
 	done
}
```

I tested it in a very ad hoc way – seems to work. If you have time you can check out if it works in your scenario, then please let me know.

If it works and you are willing, you can open a PR to the development branch and to the honours.

**Comment by bartekpacia** [comment]
Thanks! I recall something that `eval` is an antipattern in shell scripting, but I think your solution would be good enough and a justified use.

**Comment by maciejzj** [comment]
AFAIK people are discouraged from using eval because it can execute arbitrary code if it runs on user-provided data, similarly how sql injection may work.

This is a major threat in user-server scenarios with remote server or in case where the program has privileges higher than the user (e.g. the program is run with SUID of root user by guest user).

In the case of this program the purpose of the script is to pass an arbitrary markdown renderer command, if someone wishes to run any dangerous command they can do this anyways.

The only extremely unlikely scenario where `eval` would be dangerous is if someone installed `ssb` with root permissions system-wide and then attached SUID to it. Then any user would be to execute root commands via MARKDOWN_RENDERER.

This scenario seems very unlikely for a blogging system used by two people (I may be wrong).

**Comment by bartekpacia** [comment]
Thanks for explaining in more details!

> This scenario seems very unlikely for a blogging system used by two people.

Yeah, strong agree.
